project-travel-mate/Travel-Mate

README.md
fixed spelling on the README.md file
=> fixed spelling on the README.md file

.travis.yml, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/tie/hackathon/travelguide/CityFragment.java, Android/app/src/main/java/tie/hackathon/travelguide/destinations/description/FinalCityInfo.java, Android/app/src/main/java/tie/hackathon/travelguide/destinations/funfacts/FunFacts.java, Android/app/src/main/java/tie/hackathon/travelguide/destinations/funfacts/FunFactsPresenter.java, Android/app/src/main/java/tie/hackathon/travelguide/destinations/funfacts/FunFactsView.java, Android/app/src/main/java/tie/hackathon/travelguide/destinations/funfacts/FunfactFragment.java, Android/app/src/main/res/layout/activity_fun_facts.xml
1) Refactored FunFacts activity into MVP style.
2) Changes in FunFactFragment - (i) initialised ButterKnife to get the FAB click-listener working,  (ii) concatenated ".png" to the saved screenshot file name to avoid "Format not supported" while sharing on WhatsApp and other apps.
=> MVP refactoring for funfacts

APIs/bus-booking.php, APIs/get-city-hotels.php
=> Error responses changed for city hotels API

Android/app/build.gradle, Android/config/checkstyle.gradle, Android/config/quality/checkstyle_config.xml
You can use gradle task `checkstyle` to generate a report.
The report, saved as an html file,can be found at :
'app/build/reports/checkstyle/checkstyle.html'
=> Add Checkstyle

Android/app/src/main/java/tie/hackathon/travelguide/LoginActivity.java
The app was crashing on pressing Login button when credentials were empty. Also, during signup, the loader was not dismissed probably due to some response that cannot be handled. I've added the check for null credentials in both cases.
=> Check and prompt user via toast if any field is empty during login and signup.

Android/app/build.gradle, Android/build.gradle
Opened a new PR. Got a couple of conflicts while trying to squash commits in the previous PR.
=> fixed issue #65

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
hide toolbar from LoginActivity
change status bar on LoginActivity to black color
#64
=> fix issue #64

Android/app/src/main/res/layout/content_check_list.xml, Android/app/src/main/res/layout/content_citylist.xml, Android/build.gradle
=> Fixed # 82

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/res/layout/activity_login.xml, Android/app/src/main/res/values/strings.xml
Fixes #114.
@Swati4star Please review.
=> fix: Remove extra Signup/Login option

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/res/layout/activity_login.xml, Android/app/src/main/res/values/strings.xml
Fixes #123.
Screenshot:
@Swati4star Please review.
=> feat: Add confirm password field on Signup screen

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMap.java, Android/app/src/main/java/io/github/project_travel_mate/travel/MapRealTimeActivity.java, Android/app/src/main/java/utils/GPSTracker.java, Android/app/src/main/res/values/strings.xml
=> Feat : Switch GPS on in Activity

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/res/layout/nav_header_main.xml
Changes made to 2 files:
- **MainActivity.java** - add code to fetch user email id from SharedPreferences and update navigation header view to display the same; in absence of email id in the SharePreferences, the app name (_Travel Mate_) will be displayed as the default text
- **nav_header_main.xml** - changed the ID for the TextView from 'name' to 'email'
Fixes #107 
**Logged in with a dummy email ID:**
=> update NavigationView to display logged in user email id in the header

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/BugReportFragment.java, Android/app/src/main/res/drawable/edittext_background_bugreport.xml, Android/app/src/main/res/drawable/ic_bug_report_black_24dp.xml, Android/app/src/main/res/layout/fragment_bug_report.xml, Android/app/src/main/res/menu/activity_main_drawer.xml, Android/app/src/main/res/values/strings.xml
Bug Reporting Fragment with backend integration. Opening a new PR, the old one had a bunch of conflicts.
Fixes #(issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] `./gradlew assembleDebug assembleRelease`
- [ x] `./gradlew checkstyle`
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
=> Fixes Issue #98 - BugReporting

Android/app/src/main/res/layout/items_card_view.xml
=> Fixes #142

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/objects/User.java, Android/app/src/main/java/utils/DateUtils.java, Android/app/src/main/res/layout/activity_profile.xml, Android/app/src/main/res/values/strings.xml
Fetched the info from the `get-user` end-point to update the profile details.
Fixes #141 
=> feat: Use API to fill profile info

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/res/layout/activity_places_on_map.xml, Android/app/src/main/res/values/strings.xml
Added TextView indicating users that the response was empty in the Shopping screen.
<p align="center"> <img src="https://user-images.githubusercontent.com/13987465/42139214-a9e41e82-7d5f-11e8-9fdc-d115bf5b10fc.png" height=500 width=280 /> </p>
Fixes #91 
=> Added empty response handling to Shopping screen

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/CityImageSliderAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java, Android/app/src/main/res/drawable/active_dot.xml, Android/app/src/main/res/drawable/non_active_dot.xml, Android/app/src/main/res/layout/activity_final_city_info.xml
=> Fixes #135

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/res/menu/profile_menu.xml, Android/app/src/main/res/values/strings.xml
=> Fixes #172

Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsPresenter.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunfactFragment.java, Android/app/src/main/java/objects/FunFact.java, Android/app/src/main/res/layout/fragment_funfact.xml, Android/app/src/main/res/values/colors.xml, Android/app/src/main/res/values/strings.xml
Added one textview on facts screen and made some code chages related to issue.
Fixes #(issue) [#166](https://github.com/project-travel-mate/Travel-Mate/issues/166)
=> Implemented Show fact source in the City facts page 

Android/app/build.gradle, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/utils/Constants.java, Android/app/src/main/res/values/strings.xml
Profile picture can now be updated. Image is first uploaded to Cloudinary, then URL is retrieved from the cloud and finally, url is sent to server.
Fixes #156 
Ran successfully on an Android Device. Demo video is shown above.
=> Implemented update profile picture feature

Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/res/layout/activity_hotels.xml, Android/gradle/wrapper/gradle-wrapper.properties
added id for activity_hotels layout.
added Snackbar in HotelsActivity.
removed Toast in HotelsActivity.
Fixes #(issue)
#77
=> Toast to snackbar messages #77

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/res/layout/activity_my_trip_info.xml, Android/app/src/main/res/values/colors.xml, Android/app/src/main/res/values/strings.xml
=> Added option in Trip info page

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java
=> Don't show dots below image of there is only one image in city page #190

Android/app/src/main/java/io/github/project_travel_mate/utilities/ShareContactActivity.java, Android/app/src/main/res/layout/activity_share_contact.xml
=> Remove the option to share contact & create qr code by default

Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java, Android/app/src/main/res/layout/fragment_citylist.xml
Added MaterialSearchView to the CityFragment - implements auto-complete & suggestions feature.
Fixes #167 
**Additional notes**:
This might require further changes, to make the SearchView EditText appear in the toolbar instead of below it. Ran into some issues with handling the 3rd party library and inflating the SearchView into the Fragment's toolbar. Will add in the fix once I figure it out.
Many thanks to @knightcube for helping me fix the issues.
=> Add search option in the toolbar for CityFragment

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml, Android/app/src/main/res/values/strings.xml
=> Improve Add Trip screen UI #213

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java
added startActivityForResult 
Fixes #203 
=> #203 Return to MyTripFragment from AddNewTripActivity

Android/app/src/main/java/io/github/project_travel_mate/utilities/ShareContactActivity.java, Android/app/src/main/res/layout/activity_share_contact.xml, Android/app/src/main/res/values/strings.xml
=> Some changes in share contact screen #218

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java, Android/app/src/main/res/layout/fragment_my_trips.xml
added swiperefreshLayout
added action on callback method OnRefresh
Fixes #221 
=> #221 - Refresh list on swipe up

Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsAdapter.java, Android/app/src/main/res/layout/notification_listitem.xml
=> Make read & unread notification's UI different #241

Android/app/build.gradle, Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/res/drawable/ic_notifications_white.xml, README.md
=> Show count of unread notifications on notification icon in action bar

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/res/layout/activity_my_trip_info.xml, Android/app/src/main/res/values/strings.xml
Implemented feature to update trip name.
Fixes #198 
Ran Successfully on an android device.
=> trip name can now be edited

Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsActivity.java, Android/app/src/main/res/layout/activity_notifications.xml, Android/app/src/main/res/menu/read_notification_menu.xml, Android/app/src/main/res/values/strings.xml
=> Add a `mark all notifications as read` icon in Notifications page #243

Android/app/build.gradle, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelSearchDialogCompat.java, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelSearchModel.java, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelSearchModelAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/java/utils/Constants.java, Android/app/src/main/res/layout/activity_hotels.xml, Android/app/src/main/res/layout/search_list_item.xml, Android/app/src/main/res/values/colors.xml, Android/app/src/main/res/values/strings.xml, README.md
Fixes #149 
Ran successfully on an android device.
=> Implemented search dialog for cities list in hotel activity

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/java/io/github/project_travel_mate/searchcitydialog/CitySearchDialogCompat.java, Android/app/src/main/java/io/github/project_travel_mate/searchcitydialog/CitySearchModel.java, Android/app/src/main/java/io/github/project_travel_mate/searchcitydialog/CitySearchModelAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml
=> implemented search city feature in add new trip activity

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml, Android/app/src/main/res/values/strings.xml
Added SnackBar on keeping the files blank
Fixes #225 
=> #239 -  Bug Fix, App crash on keeping trip details blank

Android/app/src/main/java/io/github/project_travel_mate/utilities/ShareContactActivity.java, Android/app/src/main/res/menu/share_contact_menu.xml, Android/app/src/main/res/values/strings.xml
added menu for displaying share button
added functionality onClick share menu
Fixes #222 
=>  #222 -  Add contact share button

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsActivity.java
Fixes https://github.com/project-travel-mate/Travel-Mate/issues/266
=> Notification count & marked notification UI is not getting updated #266

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml, Android/app/src/main/res/values/strings.xml
replaced edit text with a button
added textview to show selected text
Fixes #261 
=> #261 - change edittext to button in addtrip activity

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml, Android/app/src/main/res/values/strings.xml
=> #272 - Add textview for selected City

Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java, Android/app/src/main/res/layout/activity_shopping_currentcity.xml, Android/app/src/main/res/values/strings.xml
=> Don't show anything by default on the shopping screen #270

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml
=> Don't show the progress bar initially when add trip page is opened #277

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoPresenter.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoView.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java, Android/app/src/main/res/layout/activity_hotels.xml, Android/app/src/main/res/layout/activity_my_trip_info.xml, Android/app/src/main/res/layout/activity_profile.xml, Android/app/src/main/res/values/strings.xml
=> Show appropriate animations on screens when there are no results #195

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/java/io/github/project_travel_mate/MyFriendsAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/MyFriendsFragment.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/FriendsProfileActivity.java, Android/app/src/main/res/drawable/ic_people_black_24dp.xml, Android/app/src/main/res/layout/fragment_my_friends.xml, Android/app/src/main/res/layout/friend_listitem.xml, Android/app/src/main/res/menu/activity_main_drawer.xml, Android/app/src/main/res/values/strings.xml
=> Implemented my friends' feature

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java, Android/app/src/main/res/menu/trip_info_menu.xml, Android/app/src/main/res/values/strings.xml
=>  Remove myself from trip #287

Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java, Android/app/src/main/res/layout/activity_shopping_currentcity.xml
=> Shopping page shows no internet connection error in case of no results #291

Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/res/layout/activity_hotels.xml, Android/app/src/main/res/values/strings.xml
=> Hotels page shows nothing on start #292

Android/app/src/main/res/layout/activity_profile.xml
=> Email is getting truncated in friend's profile page #297

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/FullScreenProfileImage.java, Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/FriendsProfileActivity.java, Android/app/src/main/java/utils/Constants.java, Android/app/src/main/res/layout/activity_full_profile_image.xml, Android/app/src/main/res/values/styles.xml
=> implemented full profile pic feature

Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java
=> Infinite scrolling in Fun facts view #171

Android/app/src/main/res/layout/activity_profile.xml
=> fix: Friends profile UI

Android/app/src/main/java/io/github/project_travel_mate/utilities/AboutUsFragment.java
=> App closes on pressing back from bugs fragment #281

Android/app/src/main/java/io/github/project_travel_mate/MyFriendsFragment.java
=> removed bug from friends' list

Android/app/src/main/java/io/github/project_travel_mate/destinations/CityAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/WeatherActivity.java, Android/app/src/main/res/values/strings.xml
=> created "view weather forecast" option on card view

Android/app/src/main/java/io/github/project_travel_mate/travel/MapRealTimeActivity.java, Android/app/src/main/res/layout/activity_map_realtime.xml
=> Show no internet animation in map activity #328

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java
=> Friends list is not updated after adding new friend #330

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/res/layout/activity_my_trip_info.xml
=> changed material dialog to progress bar in my trip activity

Android/app/src/main/res/layout/activity_profile.xml
=> Getting a red line below the email id #344

Android/app/src/main/java/io/github/project_travel_mate/travel/MapRealTimeActivity.java
=> The item is not checked first time on the map #342

Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java, Android/app/src/main/res/layout/activity_shopping_currentcity.xml, Android/app/src/main/res/values/strings.xml
=> Show the item name that is being searched in shopping page #343

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/layout/activity_add_new_trip.xml
=> showed animation in case of no internet in add new trip activity

Android/app/src/main/java/io/github/project_travel_mate/roompersistence/ChecklistDataSource.java, Android/app/src/main/java/io/github/project_travel_mate/roompersistence/ChecklistItemDAO.java, Android/app/src/main/java/io/github/project_travel_mate/roompersistence/ChecklistViewModel.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistFragment.java, Android/app/src/main/res/drawable/ic_delete_white_24dp.xml, Android/app/src/main/res/layout/fragment_check_list.xml, Android/app/src/main/res/menu/checklist_menu.xml, Android/app/src/main/res/values/strings.xml
=> implemented delete all tasks feature in checklist

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/res/layout/activity_my_trip_info.xml
=> removed progress bar and added animation in myTripInfo

Android/app/build.gradle, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/res/layout/activity_places_on_map.xml, Android/app/src/main/res/layout/city_infoitem.xml, README.md
=> removed twoway dependency

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java, Android/app/src/main/java/utils/ExpandableTextView.java, Android/app/src/main/res/drawable/ic_keyboard_arrow_down_black_24dp.xml, Android/app/src/main/res/drawable/ic_keyboard_arrow_up_black_24dp.xml, Android/app/src/main/res/layout/activity_final_city_info.xml, README.md
=> removed expandable textview dependency

Android/app/src/main/res/layout/activity_weather.xml
=> Updates in weather activity UI #364

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/res/drawable/ic_location_on_blue_24dp.xml, Android/app/src/main/res/drawable/ic_radio_button_checked_blue_24dp.xml, Android/app/src/main/res/layout/activity_places_on_map.xml, Android/app/src/main/res/layout/city_infoitem.xml
Fixes #154 
When no item is selected : 
When an item is selected : 
=> changed PlacesOnMap UI

Android/app/src/main/java/io/github/project_travel_mate/CitiesTravelledAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/objects/City.java, Android/app/src/main/res/layout/activity_profile.xml, Android/app/src/main/res/layout/profile_city_listitem.xml, Android/app/src/main/res/values/strings.xml
=> cities visited feature

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java
=> fixed marker setting in mapsUI

Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsActivity.java, Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsAdapter.java, Android/app/src/main/java/objects/Notification.java, Android/app/src/main/res/drawable/ic_notification_black_24dp.xml, Android/app/src/main/res/layout/notification_listitem.xml
=> Show notification date in notification #366

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java
=> Weather icon not loading for certain weather conditions #377

Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/res/layout/activity_hotels.xml, Android/app/src/main/res/layout/hotel_listitem.xml, Android/app/src/main/res/values/strings.xml
Fixes #310.
**Its overlapping if I only open first of the row**
=> Hotel list item UI #310

Android/app/src/main/res/layout/fragment_my_friends.xml, Android/app/src/main/res/layout/friend_listitem.xml
=> Change the friends page UI to have 3 friends in a row #384

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/res/drawable/ic_radio_button_checked_orange_24dp.xml, Android/app/src/main/res/layout/activity_places_on_map.xml, Android/app/src/main/res/layout/city_infoitem.xml
=> UI Bug in map activity #371

Android/app/src/main/res/layout/activity_map_realtime.xml
=> Remove extra space after card in real time activity #341

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/FriendsProfileActivity.java, Android/app/src/main/res/layout/activity_friends_profile.xml, Android/app/src/main/res/layout/activity_profile.xml
=> Changes in UI of Profile Page #391,#383

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/res/values/strings.xml
=> removed bug from myTripInfoActivity

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/res/layout/activity_profile.xml, Android/app/src/main/res/values/strings.xml
=> Limit user status characters count to 100 #394

Android/app/build.gradle, Android/app/proguard-rules.pro, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java
=> Unable to edit profile image #205

Android/app/src/main/res/layout/activity_profile.xml
=> Remove left margin from `cities visited` in user's profile #401

Android/app/src/main/java/io/github/project_travel_mate/travel/MapViewRealTimeActivity.java
=> Dont load items by default in real time locator #404

Android/app/src/main/java/io/github/project_travel_mate/SettingsFragment.java
=> Use API for `Update Password` #412

Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsActivity.java
=> Fixes The time should show month (not months) when it is single #439

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/SettingsFragment.java, Android/app/src/main/res/layout/fragment_settings.xml
Fixes #441 
Snackbar is displayed by hiding keyboard. 
Now progress is shown on "Done" button.
=> Fixed #441, keyborad now hides before displaying snackbar, progress bar for password change added

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
When I tried to do an new account on the app, I saw "?" wasn't part of the Special Character so my passwort wans't valid.
I change the regex in src\main\java\io\github\project_travel_mate\login\LoginActivity to take account of the question mark as a special character
Fixes #(issue)
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings
=> Change the Regex to include question marks in the password

CONTRIBUTING.md, README.md
Fixes #(issue)
- [x ] New feature (non-breaking change which adds functionality)
=> added contributing guidelines to the project

.github/pull_request_template.md, CONTRIBUTING.md, README.md, SETUP_GUIDELINES.md
Updated pull-request_template and added git setup guidelines
=> Contributing guidelines

Android/app/build.gradle, Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/java/io/github/project_travel_mate/travel/MapViewRealTimeActivity.java, Android/app/src/main/java/utils/Utils.java, Android/app/src/main/res/layout/activity_map_realtime.xml, Android/app/src/main/res/layout/activity_places_on_map.xml
Here are there major changes in these files
AndroidMenifest.xml -- Removed Google map API key and other meta data
build.gradle -- Removed google map dependency and added for Open street maps
activity layouts and respective activity class wherever google has been used.
New Feature #(417)
=> Replaced 'Google Maps' with 'Open Street Maps' #417

Android/app/build.gradle, Android/app/src/main/java/dao/CityDao.java, Android/app/src/main/java/database/AppDataBase.java, Android/app/src/main/java/database/Converters.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/CityFragment.java, Android/app/src/main/java/objects/City.java, Android/app/src/main/java/utils/Constants.java, Android/build.gradle
roomVersion = "1.0.0" has changed to 1.0.0-beta2 since there was gradle issue. 
Fixes #188
=> Save most popular cities offline #188

Android/app/src/main/java/adapters/RestaurantsCardViewAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/RestaurantsActivity.java, Android/app/src/main/java/utils/RestaurantItemEntity.java, Android/app/src/main/res/drawable/ic_sort.xml, Android/app/src/main/res/menu/restaurants_sort_menu.xml, Android/app/src/main/res/values/strings.xml
Added a sort functionality to restaurants. An action with a dropdown menu.
Fixes #423 
=> Added a sort functionality to restaurants

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/dao/WidgetCheckListDao.java, Android/app/src/main/java/database/AppDataBase.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistFragment.java, Android/app/src/main/java/widget/CheckListItem.java, Android/app/src/main/java/widget/CheckListProvider.java, Android/app/src/main/java/widget/CheckListWidgetProvider.java, Android/app/src/main/java/widget/CheckListWidgetService.java, Android/app/src/main/res/layout/checklist_widget.xml, Android/app/src/main/res/layout/checklist_widget_item.xml, Android/app/src/main/res/values/strings.xml, Android/app/src/main/res/xml/checklist_widget_info.xml
Added home screen widget to show selected checklists.
New Feature #118
=> [New Feature] Add checklist widget to home screen #118

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/utilities/ConversionListViewActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyConverterAdapter.java, Android/app/src/main/java/objects/CurrencyName.java, Android/app/src/main/res/layout/activity_conversion_listview.xml
=> add search bar on currency selector list #454

Android/app/build.gradle, Android/app/src/main/java/io/github/project_travel_mate/travel/ListViewRealTimeActivity.java, Android/app/src/main/java/io/github/project_travel_mate/travel/MapViewRealTimeActivity.java, Android/app/src/main/java/utils/GPSTracker.java
Fixes https://github.com/project-travel-mate/Travel-Mate/issues/455
=> Add open street map API to get location

Android/app/src/main/res/layout/restaurants_card_view.xml, Android/app/src/main/res/values/colors.xml
UI change #387 , the background change to dark similar to utilities or travel cards
Fixes #387 
=> Add darker background to restaurant items #387

README.md
Added Timeline view and Spotlight library dependencies in Readme.
Fixes #(issue)
=> Updated readme dependency list

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
Modifies the regex that validates passwords to consider underscore (`_`) as a valid special character.
Fixes #490 
=> Add underscore as a special character

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java, Android/app/src/main/res/layout/activity_hotels.xml, Android/app/src/main/res/layout/hotel_listitem.xml
Replaced GridView with RecyclerView and changed BaseAdapter to RecyclerView.Adapter with ViewHolder pattern, some little changes are also made in `hotel_listitem.xml`
Fixes #382 
=> Fixes #382: Fixed overlapping of list items in `HotelsActivity.java`

Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsActivity.java
**BEFORE:**
**AFTER:**
Fixes #496 
=> Hide "mark all as read" for user with zero notification

Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java, Android/app/src/main/res/layout/activity_utilities_currency_converter.xml, Android/app/src/main/res/values/strings.xml
Improvements done in UI , before/after snaps...
<div align="center">
</div>
Fixes #500
=> Fixes #500: App crashes fixed when the internet is inactive

Android/app/src/main/java/io/github/project_travel_mate/friend/FriendCityRecyclerAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/friend/FriendsProfileActivity.java, Android/app/src/main/java/objects/FriendCity.java, Android/app/src/main/res/layout/activity_friends_profile.xml, Android/app/src/main/res/layout/friend_city_list_item.xml, Android/app/src/main/res/values/dimens.xml
Added the cities visited labels in the profile of a person
Screenshot:
Fixes #416 
Tested on emulator and device.
=> Issue 416: Add cities visited labels in friend's profile

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java, Android/app/src/main/res/layout/fragment_my_trips.xml
Swipe refresh moved to myTrips() method, changed xml file to fix when internet connectivity disconnects which sets the visibility of views VISIBLE/GONE.
when user deletes/adds any trip onResume method updates the list.
Fixes #502
=> Fix: #502 Updated mytrips to fix duplicates

Android/app/src/main/res/layout/activity_utilities_world_clock.xml, Android/app/src/main/res/values/dimens.xml
=> Issue:513 - Bug fix for world clock utility

Android/app/src/main/java/io/github/project_travel_mate/friend/MyFriendsAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/friend/MyFriendsFragment.java, Android/app/src/main/res/layout/fragment_my_friends.xml, Android/app/src/main/res/layout/friend_listitem.xml
Replaced GridView with RecyclerView, enhanced `friend_listitem.xml` , if friend's name has alphabets more than 16 it will set 3(dots) followed by substring (as shown in screenshot below).
Fixes #405
=> Fixes #405 No more truncated friend names

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/res/drawable/ic_done_black_24dp.xml, Android/app/src/main/res/layout/activity_profile.xml
Added checks.
Fixes #520 
<div align=center >
</div>
=> Fixes #520: Added email verified check

Android/app/src/main/java/io/github/project_travel_mate/SettingsFragment.java, Android/app/src/main/res/layout/fragment_settings.xml, Android/app/src/main/res/values/strings.xml
Allow users to delete their account.
Fixes #510 
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
=> Fixes #510: Add Delete Account option in settings

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/CityMapActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java, Android/app/src/main/java/utils/Utils.java, Android/app/src/main/res/drawable/ic_map.xml, Android/app/src/main/res/drawable/ic_save.xml, Android/app/src/main/res/layout/activity_city_map.xml, Android/app/src/main/res/layout/content_city_info.xml, Android/app/src/main/res/values/strings.xml
Included an option open a city's map in the City and also CityMapActivity that shows a city's map with an option for users to save the map offline.
Also added the new activity to the manifest and a utils method to check for network connectivity.
Fixes [#(469)](https://github.com/project-travel-mate/Travel-Mate/issues/469)
=> Fix #469 Allow users to save map offline

Features.md
Greetings from Hacktoberfest event in Warsaw
Fixes #(issue)
=> Change the lowercase letter to uppercase

Android/app/src/main/java/io/github/project_travel_mate/friend/FriendsProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java, Android/app/src/main/java/io/github/project_travel_mate/notifications/NotificationsActivity.java, Android/app/src/main/java/objects/Trip.java, Android/app/src/main/res/layout/content_my_trip_info.xml, Android/app/src/main/res/values/strings.xml
Issue: https://github.com/project-travel-mate/Travel-Mate/issues/531
Task in this commit:
* Added Layout Functionality for ticket requirements.
* Added Code to display if a trip is public or private.
* Added api request when toggle button is pressed to change trip is_public status on back-end.If there are any UI change.
Fixes #531 
=> Show if a trip is public or private

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/java/io/github/project_travel_mate/SettingsFragment.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/TripsListAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CompassActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java, Android/app/src/main/java/objects/Trip.java, Android/app/src/main/java/utils/Constants.java, Android/app/src/main/res/layout/content_my_trip_info.xml, Android/app/src/main/res/layout/trip_header.xml, Android/app/src/main/res/menu/trip_info_menu.xml, Android/app/src/main/res/values/strings.xml
Share the link to trip:  The uri is in the form:
http://project-travel-mate.github.io/Travel-Mate?trip=trip_id
=> Allow users to share trip link

Android/app/src/main/java/io/github/project_travel_mate/SettingsFragment.java, Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/DailyQuotesFragment.java, Android/app/src/main/java/objects/Quote.java, Android/app/src/main/java/objects/QuoteGroup.java, Android/app/src/main/java/utils/Constants.java, Android/app/src/main/java/utils/DailyQuotesManager.java, Android/app/src/main/res/layout/activity_login.xml, Android/app/src/main/res/layout/fragment_daily_quotes.xml, Android/app/src/main/res/layout/fragment_settings.xml, Android/app/src/main/res/values/strings.xml
* Added switch button to settings to control display of daily quotes.
* Added code in LoginActivity to display Daily Quotes fragment.
* Light formatting of LoginActivity.java
* Created DailyQuotesFragment.java
* Created QuoteGroup Object class, which contains a list of Quote objects.
* Created Quote Object class, which contains a quote and author string variable.
* Added Constants to control functionality of Daily Quotes.
* Created DailyQuotesManager to manage daily quotes.
* Added FrameLayout to activity_login.xml in order to inflate with DailyQuoteFragment.
* Added String Resources to populate hard coded text on DailyQuoteFragment.
Fixes #538 
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected) …
=> Jira Ticket: Issue #538 - Show `travel quote once a day` fragment

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/VerifyEmailActivity.java, Android/app/src/main/java/utils/Constants.java, Android/app/src/main/res/layout/activity_profile.xml, Android/app/src/main/res/layout/activity_verify_email.xml, Android/app/src/main/res/values/strings.xml
Added email verification option.
Fixes #527 
=> Fixes #527: Added verify email address feature

Android/app/src/main/res/layout/activity_add_new_trip.xml
=> Swap drawable src id of location and event icons

Android/app/src/main/java/io/github/project_travel_mate/SplashActivity.java, Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/java/io/github/project_travel_mate/login/LoginView.java
Added Check for already logged in user at splash screen
=> Check User Login on Splash Screen

Android/app/src/main/java/dao/CityDao.java, Android/app/src/main/java/database/AppDataBase.java, Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/favourite/FavouriteCitiesAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/favourite/FavouriteCitiesFragment.java, Android/app/src/main/java/objects/City.java, Android/app/src/main/res/drawable/ic_favorite_black_24dp.xml, Android/app/src/main/res/drawable/ic_favorite_red_full_24dp.xml, Android/app/src/main/res/drawable/ic_favorite_white.xml, Android/app/src/main/res/layout/content_city_info.xml, Android/app/src/main/res/layout/fav_city_item.xml, Android/app/src/main/res/layout/fragment_fav_cities.xml, Android/app/src/main/res/menu/activity_main_drawer.xml, Android/app/src/main/res/values/strings.xml
I added new function to app - Favourite cities. There is new fragment "Favourite cities" which we can open from Navigation Drawer. User can toggle favourite city from FinalCityInfoActivity by clicking on heart. Info about favourite cities are stored in database (Roompersistence library). Also migration from version 2 to 3 was added.
fixes https://github.com/project-travel-mate/Travel-Mate/issues/224
=> Add favourite cities

Android/app/src/main/java/io/github/project_travel_mate/travel/HotelsActivity.java
More than 10 cities enabled.
Fixes #262 
=> More than 10 cities enabled.

README.md
Found and solved the typo error in README.md file.
Fixes #572 
=> fix: Fixed the Typo error

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java
=> Fix #576 My Trip list doesn't refreshes its content after deleting the last trip

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java, Android/app/src/main/res/values/strings.xml
=> Fix #580 Pressing back button in any of the fragment leads to app close

Android/app/src/main/res/layout/fragment_my_friends.xml, Android/app/src/main/res/layout/fragment_my_trips.xml
Fixed Background issue with trips and friends fragments at Home.
Fixes #618 
=> Fixed Background issue with trips and friends fragments

Android/app/src/main/res/layout/activity_profile.xml, Android/app/src/main/res/values/strings.xml
Set the word limit to 50  for the username  input box.
Fixes #607 
=> Set the word limit for the username input box

Android/app/src/main/AndroidManifest.xml
Fixed behavior of display Name in Profile Activity
Fixes #623 
=> Fixed behavior of display Name in Profile Activity

Android/app/src/main/java/flipviewpager/view/FlipViewPager.java
Fixed the UI/UX and the card is opening open.
Fixes #621 
=> Bug fix in View Page flipper transformation

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/TweetsDescriptionAdapter.java, Android/app/src/main/res/layout/tweets_description_listitem.xml
Fixed crash on clicking hashtag bug.
Fixes #619 
=> Fixed crash on clicking hashtag bug.

Android/build.gradle, Android/gradle/wrapper/gradle-wrapper.properties
Updated the Gradle version to the recent versions.
Fixes #635 
=> Upgraded the gradle version 

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java
Fixed App crash while clicking on a trip.
Fixes #636 
=> Fixed App crash while clicking on a trip

Android/app/src/main/java/io/github/project_travel_mate/login/LoginPresenter.java
Fixed password reset error
Fixes #630 
=> Fixed password reset error

Android/app/src/main/java/io/github/project_travel_mate/SettingsFragment.java, Android/app/src/main/res/layout/fragment_settings.xml
I did some changes in the code in order to see the errors in the settings form properly.
Fixes #651
=> FIX #651 Error symbol cannot be seen properly

Android/app/src/main/res/layout/activity_utilities_world_clock.xml
The user was not able to view the screen contents as scrolling was not available when the user switches the view from portrait to landscape mode. Scrolling is now enabled.
Fixes #650 
=> Scrolling enabled in landscape view also

Android/app/src/main/res/layout/activity_login.xml
Scrolling enabled now and works for the user providing usage of login screen even in landscape mode.
Fixes #672 
=> feature enabled

Android/app/src/main/res/layout/fragment_settings.xml
Scrolling now working in landscape mode also.
Fixes #679 
=> Scroll working

README.md
Opening paragraph needs to be reworded as the use of "from ...to" indicates a range of extremes rather than listing examples, which is the desired message. The fix can be made by removing either of the second features, or by changing "from" to "including" and removing the "to" between the features.  Reword last sentence of opening paragraph: "every possible solution" sets an unrealistic expectation for the app.  Reworded "How Travel Mate Works" section. Removed superfluous words, adverbs, and adjectives that didn't add useful information ie: basically. Removed the last sentence as the three phases are not clearly identified for the user.
Fixes #(issue)
README doc changes, no changes to …
=> Issue #687: Update README doc.

Android/app/build.gradle, Android/app/src/androidTest/java/io/github/project_travel_mate/ApplicationTest.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java, Android/app/src/main/res/values/strings.xml, Android/build.gradle
Fixes #681 
It will also fix a build error, related with test classes
Fixes #(issue)
=> Show alert in addTrip avtivity when the selected date is before today

CONTRIBUTING.md
Fixes broken link in CONTRIBUTING.md
Fixes #689 
=> Fix #689 Update Travis link in CONTRIBUTING.md

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java
When I selected a future date of the current month on add new trip screen it gives error snack bar. But when I selected next month date it works fine. So I have fixed that when we selected any future date of any month. It works fine.
Fixes #703
=> Fixes #703 fixes trip future date issue in AddNewTripActivity.java

Android/build.gradle
Change for issue #701
Updated Kotlin version to the latest (1.3.50).
Fixes #701 
- [] Bug fix (non-breaking change which fixes an issue)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> Fix #701 Updated kotlin version to the latest (1.3.50)

Android/app/build.gradle, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/TweetsDescriptionAdapter.java
updated playstore version; fixed few crashes
=> updated playstore version; fixed few crashes

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/CityMapActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java, Android/build.gradle
=> Up navigation fun facts activity

Android/app/src/main/java/io/github/project_travel_mate/destinations/funfacts/FunFactsActivity.java
Replaced Objects#requireNonNull with simple null check. It seems like this is enough to be able to open the fun fact without any problems.
Fixes #729
=> #729-Fix NPE in FunFactsActivity.java

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
Fixes https://github.com/project-travel-mate/Travel-Mate/issues/738
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ x] `./gradlew assembleDebug assembleRelease`
- [ x] `./gradlew checkstyle`
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My changes generate no new warnings
=> Removed Password Validation | Solves #738

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/FinalCityInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/TweetsDescriptionAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/favourite/FavouriteCitiesAdapter.java, Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/TimezoneListViewActivity.java, Android/app/src/main/java/objects/UpcomingWeekends.java, Android/app/src/main/java/widget/CheckListWidgetProvider.java, Android/app/src/main/java/widget/ClockWidgetConfigureActivity.java
Refactor deprecated code like setRemoteAdapter and getDrawable
delete all unused import's
=> Refactor deprecated code and delete un used imports

Android/app/src/main/res/layout/fragment_home.xml
Fix utilities_home position in landscape mode
=> Fix utilities_home CardView position in landscape mode

Android/app/src/main/java/utils/DailyQuotesManager.java
Daily quotes page was shown to user every time the app was opened. Now, it is shown once a day.
Fixes #755 
=> Fixed daily quotes to be shown only once a day. Closes #755

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/java/io/github/project_travel_mate/login/LoginPresenter.java, Android/app/src/main/java/io/github/project_travel_mate/login/LoginView.java
add checking before show toast message "your password has been reset. Login with the new password" when back to login from reset password ui
Fixes #697 
=> #697 - fix toast message is showing when navigating back to login

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java, Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripInfoActivity.java, Android/app/src/main/java/io/github/project_travel_mate/travel/MapViewRealTimeActivity.java, Android/app/src/main/java/io/github/project_travel_mate/travel/TravelFragment.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CustomAnalogClock.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/UtilitiesFragment.java
Refactor deprecated codes in CustomAnalogClock, ProfileActivity, MapViewRealTimeActivity, MyTripInfoActivity and PlacesOnMapActivity
Fixes #(issue)
=> Refactor deprecated code

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java, Android/app/src/main/res/layout/bottomsheet_map_cards.xml
The code has been cloned properly this time with all the recommendations.
Please review.
=> Updated place on map activity

README.md
A typo and grammar issue fixed in Readme.md
It provide -> It provides
=> Minor typo fixed in README

Android/app/src/main/AndroidManifest.xml, Android/app/src/main/java/io/github/project_travel_mate/TravelMateApplication.java, Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyConverterAdapter.java
I created a custom application implementation so we could initialize every third party libraries that need to be initialized once during the whole application lifecycle.
⚠️ It may looks weird, but you'll now see a "All World data loaded" Toast upon startup. This Toast should disapear as soon as we upgrade to the 1.3 version of the worldCountryData library but this release is currently unavailable on Jitpack (see blongho/worldCountryData#4).
Fixes #781
=> #781 - Create the application implementation

Android/app/src/main/java/io/github/project_travel_mate/utilities/DailyQuotesFragment.java
Hide the "Don't show again" checkbox before screenshot
Fixes #785
=> #785 - Hide the "Don't show again" checkbox before screenshot

Android/app/src/main/java/adapters/ContributorsAdapter.java
Update ContributorsAdapter to use @BindView with ViewHolder class.
Whit this all adaptors (where applicable) within the adaptors folder are using butterknife.
Fixes #(issue)
=> #780 - ContributorsAdapter replace findViewById with @BindView

.travis.yml, Android/app/src/test/java/utils/DateUtilsTest.java
Create tests for the DateUtils class
Fixes #787 
=> Create tests for the DateUtils class

Android/app/src/main/java/io/github/project_travel_mate/MainActivity.java
Check if network is available before show quote
Fixes #795 
=> Check network before load quote from API to save time if not network

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java, Android/app/src/main/res/values/strings.xml
Added snackbar prompt to notify user when email address is invalid
Added snackbar prompt to inform the user of an invalid email address during signup, prompt message added to strings.xml
Fixes #805 
=> #805 - Added snackbar prompt for invalid email during signup
