APIs/bus-booking.php
APIs/inc/responses/errors.php
APIs/places-api.php

I believe an "r" is missing in the function name :P

APIs: fix typo in function names

---

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
Android/app/src/main/java/io/github/project_travel_mate/login/LoginPresenter.java
Android/app/src/main/java/io/github/project_travel_mate/login/LoginView.java
Android/build.gradle

user redirected to login after signup

---

Android/app/src/main/assets/icons.json

Weather icon not loading for haze condition #362

---

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/RestaurantsActivity.java

This pull request adds the code for showing empty state in ```RestaurantsActivity``` when it gets a response of ```Not Found``` from the API endpoint.
Fixes #473 

Fixed issue #473 of showing empty state in restaurants activity

---

.travis.yml
Android/app/build.gradle
Android/build.gradle

I upgrade the project to SDK 28 and removed the `buildToolsVersion` field, because is not needed from android gradle plugin 3.0.0 and up, see [here](https://developer.android.com/studio/releases/build-tools):
> If you're using Android plugin for Gradle 3.0.0 or higher, your project automatically uses a default version of the build tools that the plugin specifies
After upgrade I tested and it crash because of lottie lib:
```
ava.lang.IllegalArgumentException: Invalid Layer Save Flag - only ALL_SAVE_FLAGS is allowed
at android.graphics.Canvas.checkValidSaveFlags(Canvas.java:378)
at android.graphics.Canvas.saveLayer(Canvas.java:455)
at com.airbnb.lottie.model.layer.BaseLayer.draw(BaseLayer.java:224)
at com.airbnb.lottie.model.layer.CompositionLayer.drawLayer(CompositionLayer.java:100)
at …
```

Upgrade to sdk 28

---

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java
Android/app/src/main/java/io/github/project_travel_mate/mytrips/TripsListAdapter.java

This pull request fixes the issue where duplicate trips get added on swiping to refresh. The PR sets refreshing to true in onRefresh, and sets it to false in onResponse of the OkHttp Call. Also, it updates the adapter accordingly.
Fixes #502 

Fix duplicate trips getting added on refreshing

---

Android/app/src/main/res/layout/contributors_gridview_item.xml
Android/app/src/main/res/layout/fragment_contributors.xml

Changed `contributors_gridview_item.xml`  to ellipsize contributor's name if they are long
Fixes #521 

Fixes #521 Contributor's name are single lined

---

Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java
Android/app/src/main/res/layout/activity_utilities_currency_converter.xml
Android/app/src/main/res/values/strings.xml

Added Spinner to CurrencyActivity || navigation drawer -> utilities -> currency converter
Referring to issue #522 (Currency converter : Make number of days customizable in trends graph)
fixes #522
**Initial Screen**  
**Convert Button Pressed**
**Dropdown button pressed**
**1 Year selected**
- [x ] New feature (non-breaking change which adds functionality)

Added spinner to customize number of days in trends graph

---

Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistAdapter.java
Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistDragCallback.java
Android/app/src/main/java/io/github/project_travel_mate/utilities/ChecklistFragment.java

Initially I planned to have two different adapters, but later went with a boolean flag in the adapter. So the name should simply be `ChecklistAdapter` rather than `ChecklistPendingAdapter` to avoid confusion. I missed renaming it in my previous PR.

minor: Refactor ChecklistPendingAdapter to ChecklistAdapter

---

Android/app/src/main/java/io/github/project_travel_mate/mytrips/MyTripsFragment.java

Snackbar duration is set to short
Fixes #577 

Fix 577 Snackbar is displayed for very long duration in my trips section

---

Android/app/src/main/java/io/github/project_travel_mate/login/LoginActivity.java
Android/app/src/main/res/layout/activity_login.xml

Replaced SnackBar which is not visible with an "Invalid Email" error message on Edit Text when a user gives wrong input.
Fixes #(issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] My changes generate no new warnings

Improve UX of Signup Screen

---

Android/app/src/main/res/layout/activity_my_trip_info.xml

This change prevents the "FloatingActionBar - know_more" from
covering the "share" & "menu" icons when collapsing.
Fixes #(issue)
Resolves #600

Add "collapseMode - parallax" to "FAB - know_more"

---

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/PlacesOnMapActivity.java

When clicking on more button in Nearby Places, the app redirects the user to the blank Google page instead of the google page with the query set as the selected monument.
Fixes #633

Fixed google search bug.

---

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/RestaurantDetailsActivity.kt

Checking if the url string for a restaurant is empty before attempting to load the url with Picasso in RestaurantDetailsActivity.
Fixes #628 
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My changes generate no new warnings

Fixes #628 - Adding empty check to restaurant image url string in RestaurantDetailsActivity

---

Android/app/src/main/java/io/github/project_travel_mate/travel/ShoppingCurrentCityActivity.java
Android/build.gradle

I fixed screen orientation for ShoppingCurrentCityActivity. I added method onSaveInstanceState where I save instances for listview and city name. I had to declare local variable mFeedItems, where I store originally feedItems, because I need to pass it to outState when activity is destroyed(screen orientation changes). In method onCreate I pass it back to variable, and I recreate view.
Fixes #632
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] `./gradlew checkstyle`
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

fixed screen orientation in ShoppingCurrentCityActivity

---

Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java

If the error animation is showing (i.e. Visible) onBackPressed() calls the cancelAnimation method which results in Currency Converter Activity not getting destroyed, and user is not required to do currency conversion from beginning as mentioned in #702 
Fixes #702
- A JSONException was explicitly thrown to produce the error and check if everything is working as expected, the code worked as expected. 

Fixes Issue #702

---

Android/app/src/main/java/io/github/project_travel_mate/mytrips/AddNewTripActivity.java

Fixed "add trip" which was previously not working. The error was because of using a deprecated constructor. Used the calendar class to fix it.
Fixes #(issue)

fixed add trip integer out of range

---

Android/app/src/main/java/io/github/project_travel_mate/utilities/CurrencyActivity.java
Android/app/src/main/res/layout/activity_utilities_currency_converter.xml

I tried with `ConstraintLayout` but it doesn't work that well, and still see some issue in lower-dpi and small screen sizes. I decided to wrap the whole view under `NestedScrollView` so it can still be scrollable even when the button got pushed out of screen.
Also accommodate this change by changing ButterKnife Binding inside `CurrencyActivity`, specifically changing type of `R.id.actual_layout` to `View` instead of `RelativeLayout`. I think this is better approach as well since the best practice is to make the binding as generic as possible. For example, if you don't need `RelativeLayout` specific functions, then it can be used as `View` or `ViewGroup`. This allows you to update the layout easily, say in future, you want it to be `LinearLayout`, you don't need to touch the actual …

#626-Wrap views under NestedScrollView to allow seeing full view in landscape

---

Android/app/src/main/java/io/github/project_travel_mate/destinations/description/CityImageSliderAdapter.java
Android/app/src/main/res/layout/activity_city_info.xml

Add black contrast to images in slider to fix city name when background is white or default image
Fixes #748 

Add black contrast to the slider

---

Android/app/src/main/res/layout/activity_login.xml

Resolves #654 
Adjusted the `forgot_password` text to appropriately align below the `sign up` text. Before it would be squashed when in landscape on some devices.
Fixes #(issue)

Fixed an issue where the `forgot_password` textview would be pushed off the screen by the `signup` textview when in landscape.

---

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java
Android/app/src/main/res/layout/activity_profile.xml

Show Default Status as hint in ProfileActivity to make easy to new user to add status without delete the text in first time and show hint when user remove old status
fixes #761

ProfileActivity convert default status from text to hint

---

Android/app/src/main/java/flipviewpager/view/FlipViewPager.java
Android/app/src/main/java/io/github/project_travel_mate/destinations/CityAdapter.java
Android/app/src/main/java/io/github/project_travel_mate/favourite/FavouriteCitiesFragment.java

- Add onClickListener to city in FavouriteCitiesFragment  to open CityInfo
- Remove listeners for left and right layout because it open city directly when click or touch with move
- Fix position in FlipViewPager to make user open Right city when click on it not Left City

Fix click item on City in FavouriteCitiesFragment and fix position in FlipViewPager

---

README.md

Use absolute paths instead of relative paths for images in README.md so that they are displayed properly on the github pages for the repository.
Fixes #768

docs: Use absolute instead of relative paths for images

---

Android/app/build.gradle
Android/app/lint.xml

I added lint.xml file to ignore all of the weather drawables.  Now, the weather drawables won't show up if we check for unused drawables in IDE.
Fixes #736 

#736-Weather forecast drawables shouldn't show up in "unused resources"

---

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java

- Check user Internet state and show user information from SharedPreferences if user is offline
- Make SharedPreferences update file once not for every addition it will work in 1ms not 3ms in old code
- Delete unused User class instance
Fixes #775

Make ProfileActivity work in offline mode

---

Android/app/src/main/java/adapters/TimezoneAdapter.java
Android/app/src/main/java/io/github/project_travel_mate/utilities/WorldClockActivity.java
Android/app/src/main/java/io/github/project_travel_mate/utilities/helper/FlagHelper.kt
Android/app/src/main/java/io/github/project_travel_mate/utilities/helper/KeyboardHelper.kt
Android/app/src/main/res/layout/activity_utilities_world_clock.xml
Android/app/src/main/res/layout/item_timezone.xml
Android/app/src/main/res/values/strings.xml

I took some time to rework the world clock UI.
It doesn't use a Spinner anymore but an AutoCompleteTextView which allow the user to type in the researched timezone.
Data we're manipulating right here are timezones and not countries. Flag is deducted from timezone with this algorithm : 
`
String country = timezone.contains("/") ? timezone.split("/")[1] : timezone;
`
Some countries doesn't exists in the World library so it will display a globe if the required country doesn't exists (see screenshot number 3)
⚠️ I decided to keep each feature in its own branch. Please be sure to merge #783 before this one.
If you want to test it locally, please cherrypick c3c85aee4fcc3a5b2d21d52cbe2b56c154e8cca0 to make sur that the World library is loaded.
Fixes #737 …

#737 - World clock UI update

---

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java

hide visited cities in offline mode profile activity because we can't load Cities in offline mode
Fixes #794 

Hide citiesTravelledHeading in offline mode

---

Android/app/src/main/java/io/github/project_travel_mate/ProfileActivity.java
Android/app/src/main/res/values/strings.xml

All views will be gone when user can't upload profile picture to server but the right solution is to show state toast that he can't update profile picture 
Fixes #(issue)

Fix upload profile picture issue

---

Android/app/src/main/java/io/github/project_travel_mate/destinations/CityAdapter.java

The bug is being caused in the CityAdapter class by the getPagesCount() method returning the total number of cities as the page count (in this case 10), there are 10 items (cities) each with three pages only. A class constant has been created and is returned by getPageCount to avoid any behaviour changes that may affect other code.
Fixes #803 
Built, run and tested to confirm bug fixed.

#803-FlipViewPager has an issue with the number of pages
